{{- if .Values.nginx.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "alloy.nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alloy.nginx.labels" . | nindent 4 }}
spec:
  host: {{ .Values.nginx.route.hostname }}
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ include "alloy.nginx.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
