apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alloy-gateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alloy-gateway.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- tpl .Values.nginxConfig . | nindent 4 }}
