{{- if and .Values.rbac.enabled .Values.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "alloy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "alloy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
