apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- tpl .Values.nginxConfig . | nindent 4 }}
